#!/usr/bin/env python3
import cases
import random 

def print_drop_rates():
    t = '''
    skin drop rates:
    Consumer Grade (Common Skins) - 79.92%
    Industrial Grade (Uncommon Skins) - 15.98%
    Mil-Spec (Rare Skins) - 3.2%
    Restricted (Mythical Skins) - 0.64%
    Classified (Legendary Skins) - 0.32%
    Covert (Exceedingly Rare Skins) - 0.16%
    Knives and Gloves (Ultra-Rare Items) - ~0.25% or lower (estimated)
    '''
    print(t)

def open_case(case):
    total_chance = sum(item["chance"] for item in case)
    random_value = random.uniform(0,total_chance)
    cumulative_chance = 0

    for item in case:
        cumulative_chance += item["chance"]
        if random_value < cumulative_chance:
            return item["name"]

print(open_case(cases.kilowatt_case))